---
driver:
  name: dokken
  chef_version: latest
  data_image: bluth-company/kitchen-cache

provisioner:
  name: dokken

transport:
  name: dokken

verifier:
  name: inspec

platforms:
- name: centos-7
  driver:
    image: centos:7

- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04

suites:
  - name: default
